package geo

// Country data is embedded rather than imported. The registry needs
// alpha-2, alpha-3, a canonical name, and a region for roughly 200
// entities. A third-party library would supply the same strings at the
// cost of a module dependency whose API changes across minor versions.
// This table is deterministic and compiles forever.

type countryRec struct {
	Alpha2 string
	Alpha3 string
	Name   string
	Region string
}

var countryData = []countryRec{
	{"AF", "AFG", "Afghanistan", "Asia"},
	{"AL", "ALB", "Albania", "Europe"},
	{"DZ", "DZA", "Algeria", "Africa"},
	{"AO", "AGO", "Angola", "Africa"},
	{"AR", "ARG", "Argentina", "Americas"},
	{"AM", "ARM", "Armenia", "Asia"},
	{"AU", "AUS", "Australia", "Oceania"},
	{"AT", "AUT", "Austria", "Europe"},
	{"AZ", "AZE", "Azerbaijan", "Asia"},
	{"BH", "BHR", "Bahrain", "Asia"},
	{"BD", "BGD", "Bangladesh", "Asia"},
	{"BY", "BLR", "Belarus", "Europe"},
	{"BE", "BEL", "Belgium", "Europe"},
	{"BO", "BOL", "Bolivia", "Americas"},
	{"BA", "BIH", "Bosnia and Herzegovina", "Europe"},
	{"BW", "BWA", "Botswana", "Africa"},
	{"BR", "BRA", "Brazil", "Americas"},
	{"BG", "BGR", "Bulgaria", "Europe"},
	{"BF", "BFA", "Burkina Faso", "Africa"},
	{"BI", "BDI", "Burundi", "Africa"},
	{"KH", "KHM", "Cambodia", "Asia"},
	{"CM", "CMR", "Cameroon", "Africa"},
	{"CA", "CAN", "Canada", "Americas"},
	{"CF", "CAF", "Central African Republic", "Africa"},
	{"TD", "TCD", "Chad", "Africa"},
	{"CL", "CHL", "Chile", "Americas"},
	{"CN", "CHN", "China", "Asia"},
	{"CO", "COL", "Colombia", "Americas"},
	{"CG", "COG", "Congo", "Africa"},
	{"CD", "COD", "Democratic Republic of the Congo", "Africa"},
	{"CR", "CRI", "Costa Rica", "Americas"},
	{"CI", "CIV", "Côte d'Ivoire", "Africa"},
	{"HR", "HRV", "Croatia", "Europe"},
	{"CU", "CUB", "Cuba", "Americas"},
	{"CY", "CYP", "Cyprus", "Europe"},
	{"CZ", "CZE", "Czechia", "Europe"},
	{"DK", "DNK", "Denmark", "Europe"},
	{"DO", "DOM", "Dominican Republic", "Americas"},
	{"EC", "ECU", "Ecuador", "Americas"},
	{"EG", "EGY", "Egypt", "Africa"},
	{"SV", "SLV", "El Salvador", "Americas"},
	{"ER", "ERI", "Eritrea", "Africa"},
	{"EE", "EST", "Estonia", "Europe"},
	{"ET", "ETH", "Ethiopia", "Africa"},
	{"FI", "FIN", "Finland", "Europe"},
	{"FR", "FRA", "France", "Europe"},
	{"GA", "GAB", "Gabon", "Africa"},
	{"GM", "GMB", "Gambia", "Africa"},
	{"GE", "GEO", "Georgia", "Asia"},
	{"DE", "DEU", "Germany", "Europe"},
	{"GH", "GHA", "Ghana", "Africa"},
	{"GR", "GRC", "Greece", "Europe"},
	{"GT", "GTM", "Guatemala", "Americas"},
	{"GN", "GIN", "Guinea", "Africa"},
	{"HT", "HTI", "Haiti", "Americas"},
	{"HN", "HND", "Honduras", "Americas"},
	{"HU", "HUN", "Hungary", "Europe"},
	{"IS", "ISL", "Iceland", "Europe"},
	{"IN", "IND", "India", "Asia"},
	{"ID", "IDN", "Indonesia", "Asia"},
	{"IR", "IRN", "Iran", "Asia"},
	{"IQ", "IRQ", "Iraq", "Asia"},
	{"IE", "IRL", "Ireland", "Europe"},
	{"IL", "ISR", "Israel", "Asia"},
	{"IT", "ITA", "Italy", "Europe"},
	{"JM", "JAM", "Jamaica", "Americas"},
	{"JP", "JPN", "Japan", "Asia"},
	{"JO", "JOR", "Jordan", "Asia"},
	{"KZ", "KAZ", "Kazakhstan", "Asia"},
	{"KE", "KEN", "Kenya", "Africa"},
	{"KP", "PRK", "North Korea", "Asia"},
	{"KR", "KOR", "South Korea", "Asia"},
	{"KW", "KWT", "Kuwait", "Asia"},
	{"KG", "KGZ", "Kyrgyzstan", "Asia"},
	{"LA", "LAO", "Laos", "Asia"},
	{"LV", "LVA", "Latvia", "Europe"},
	{"LB", "LBN", "Lebanon", "Asia"},
	{"LY", "LBY", "Libya", "Africa"},
	{"LT", "LTU", "Lithuania", "Europe"},
	{"LU", "LUX", "Luxembourg", "Europe"},
	{"MG", "MDG", "Madagascar", "Africa"},
	{"MW", "MWI", "Malawi", "Africa"},
	{"MY", "MYS", "Malaysia", "Asia"},
	{"ML", "MLI", "Mali", "Africa"},
	{"MT", "MLT", "Malta", "Europe"},
	{"MR", "MRT", "Mauritania", "Africa"},
	{"MX", "MEX", "Mexico", "Americas"},
	{"MD", "MDA", "Moldova", "Europe"},
	{"MN", "MNG", "Mongolia", "Asia"},
	{"ME", "MNE", "Montenegro", "Europe"},
	{"MA", "MAR", "Morocco", "Africa"},
	{"MZ", "MOZ", "Mozambique", "Africa"},
	{"MM", "MMR", "Myanmar", "Asia"},
	{"NA", "NAM", "Namibia", "Africa"},
	{"NP", "NPL", "Nepal", "Asia"},
	{"NL", "NLD", "Netherlands", "Europe"},
	{"NZ", "NZL", "New Zealand", "Oceania"},
	{"NI", "NIC", "Nicaragua", "Americas"},
	{"NE", "NER", "Niger", "Africa"},
	{"NG", "NGA", "Nigeria", "Africa"},
	{"MK", "MKD", "North Macedonia", "Europe"},
	{"NO", "NOR", "Norway", "Europe"},
	{"OM", "OMN", "Oman", "Asia"},
	{"PK", "PAK", "Pakistan", "Asia"},
	{"PS", "PSE", "Palestine", "Asia"},
	{"PA", "PAN", "Panama", "Americas"},
	{"PG", "PNG", "Papua New Guinea", "Oceania"},
	{"PY", "PRY", "Paraguay", "Americas"},
	{"PE", "PER", "Peru", "Americas"},
	{"PH", "PHL", "Philippines", "Asia"},
	{"PL", "POL", "Poland", "Europe"},
	{"PT", "PRT", "Portugal", "Europe"},
	{"QA", "QAT", "Qatar", "Asia"},
	{"RO", "ROU", "Romania", "Europe"},
	{"RU", "RUS", "Russia", "Europe"},
	{"RW", "RWA", "Rwanda", "Africa"},
	{"SA", "SAU", "Saudi Arabia", "Asia"},
	{"SN", "SEN", "Senegal", "Africa"},
	{"RS", "SRB", "Serbia", "Europe"},
	{"SL", "SLE", "Sierra Leone", "Africa"},
	{"SG", "SGP", "Singapore", "Asia"},
	{"SK", "SVK", "Slovakia", "Europe"},
	{"SI", "SVN", "Slovenia", "Europe"},
	{"SO", "SOM", "Somalia", "Africa"},
	{"ZA", "ZAF", "South Africa", "Africa"},
	{"SS", "SSD", "South Sudan", "Africa"},
	{"ES", "ESP", "Spain", "Europe"},
	{"LK", "LKA", "Sri Lanka", "Asia"},
	{"SD", "SDN", "Sudan", "Africa"},
	{"SE", "SWE", "Sweden", "Europe"},
	{"CH", "CHE", "Switzerland", "Europe"},
	{"SY", "SYR", "Syria", "Asia"},
	{"TW", "TWN", "Taiwan", "Asia"},
	{"TJ", "TJK", "Tajikistan", "Asia"},
	{"TZ", "TZA", "Tanzania", "Africa"},
	{"TH", "THA", "Thailand", "Asia"},
	{"TN", "TUN", "Tunisia", "Africa"},
	{"TR", "TUR", "Turkey", "Asia"},
	{"UG", "UGA", "Uganda", "Africa"},
	{"UA", "UKR", "Ukraine", "Europe"},
	{"AE", "ARE", "United Arab Emirates", "Asia"},
	{"GB", "GBR", "United Kingdom", "Europe"},
	{"US", "USA", "United States", "Americas"},
	{"UY", "URY", "Uruguay", "Americas"},
	{"UZ", "UZB", "Uzbekistan", "Asia"},
	{"VE", "VEN", "Venezuela", "Americas"},
	{"VN", "VNM", "Vietnam", "Asia"},
	{"YE", "YEM", "Yemen", "Asia"},
	{"ZM", "ZMB", "Zambia", "Africa"},
	{"ZW", "ZWE", "Zimbabwe", "Africa"},
}
